audio:
  input:
    device_index: 0
    language: fr
    sensitivity: 5
    silence_duration: 1.5
    timeout: 30
    vad_aggressiveness: 2
    whisper_model: small
  output:
    device_index: null
    speed: 0.6
    volume: 90
interface:
  background: images/One_piece.jpg
  background_opacity: 25
  panels:
    camera_visible: false
    debug_visible: false
    voice_lab_visible: false
  theme: dark
llm:
  model: dolphin-mistral:7b
  presets: {}
  role: assistant_general
  temperature: 0.7
system:
  language: fr
  log_level: DEBUG
voice:
  display_name: Samantha
  edge_voice: fr-FR-DeniseNeural
  embedding_path: null
  personality: GoogleFR
  sample_path: null
  tts_model: edge-tts
